sudo: false
branches:
  only:
  - master
  - stable

jobs:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
      directories:
        - node_modules
      script:
        - npm lint
        - npm run test
      after_failure:
        - cat travis.log
